# Generated by Django 4.2.16 on 2026-03-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_user', models.CharField(blank=True, max_length=50, verbose_name='访问用户')),
                ('sec_key', models.CharField(blank=True, max_length=50, verbose_name='访问密钥')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('url', models.CharField(blank=True, max_length=100, verbose_name='访问URL')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='访问地理位置')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=50, verbose_name='工具名称')),
                ('tool_ename', models.CharField(max_length=50, unique=True, verbose_name='工具英文名称')),
                ('tool_code', models.CharField(max_length=10, verbose_name='工具代码')),
                ('tool_class', models.CharField(max_length=20, verbose_name='工具分类')),
                ('tool_api', models.CharField(blank=True, max_length=100, verbose_name='工具接口')),
                ('tool_dec', models.TextField(blank=True, verbose_name='工具描述')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('like_count', models.IntegerField(default=0, verbose_name='喜欢的人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次调用时间')),
            ],
        ),
        migrations.CreateModel(
            name='ToolsClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_class', models.CharField(max_length=50, verbose_name='工具类别')),
                ('tool_class_ename', models.CharField(max_length=50, unique=True, verbose_name='工具分类英文名称')),
                ('tool_class_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
