# Generated by Django 4.2.16 on 2026-03-23 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='作者名')),
                ('author_nickname', models.CharField(max_length=50, verbose_name='作者昵称')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('permissions', models.CharField(choices=[('0', '管理员'), ('1', '普通用户')], max_length=10, verbose_name='权限')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='python', max_length=50, unique=True, verbose_name='标签')),
                ('describe', models.TextField(default='无描述', max_length=1000, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('location', models.CharField(max_length=10, verbose_name='创建地点')),
                ('quote', models.CharField(default='原创', max_length=200, verbose_name='引用')),
                ('article_class', models.CharField(default='python', max_length=50, verbose_name='分类')),
                ('article_lead', models.TextField(verbose_name='文章内容')),
                ('article_reads', models.IntegerField(default=0, verbose_name='阅读人数')),
                ('article_likes', models.IntegerField(default=0, verbose_name='喜欢人数')),
                ('article_collects', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('cornerite', models.CharField(blank=True, choices=[('J', '推荐'), ('H', '热门'), ('C', '原创')], max_length=10, verbose_name='左包角')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_avtive', models.BooleanField(default=True, verbose_name='是否可用')),
                ('remarks', models.TextField(blank=True, max_length=100, verbose_name='备注')),
                ('article_tags', models.ManyToManyField(blank=True, to='mine_api.tags', verbose_name='标签')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_article', to='mine_api.author', verbose_name='作者')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
    ]
