# Generated by Django 4.2.16 on 2026-03-23 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, unique=True, verbose_name='类名')),
                ('class_name_cn', models.CharField(max_length=50, unique=True, verbose_name='类中文名')),
                ('class_code', models.IntegerField(unique=True, verbose_name='类代码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='SiteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, unique=True, verbose_name='组')),
                ('group_code', models.IntegerField(unique=True, verbose_name='组代码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('url', models.CharField(max_length=500, verbose_name='URL地址')),
                ('url_reads', models.IntegerField(default=0, verbose_name='点击量')),
                ('url_likes', models.IntegerField(default=0, verbose_name='喜欢数')),
                ('url_collects', models.IntegerField(default=0, verbose_name='收藏数')),
                ('is_onhome', models.BooleanField(default=True, verbose_name='是否显示在主页')),
                ('describe', models.TextField(blank=True, max_length=1000, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('url_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nav_api.siteclass', to_field='class_name', verbose_name='主分类')),
                ('url_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nav_api.sitegroup', to_field='group_name', verbose_name='分组')),
            ],
        ),
    ]
