CREATE TABLE IF NOT EXISTS daily_issues (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  issue_date DATE NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  one_line TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS daily_items (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  issue_id BIGINT NOT NULL,
  rank_num INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary TEXT NOT NULL,
  FOREIGN KEY (issue_id) REFERENCES daily_issues(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS daily_top10 (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  issue_id BIGINT NOT NULL,
  rank_num INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary TEXT NOT NULL,
  FOREIGN KEY (issue_id) REFERENCES daily_issues(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS daily_trends (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  issue_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  predict_time VARCHAR(32) NOT NULL,
  probability INT NOT NULL,
  reason TEXT NOT NULL,
  FOREIGN KEY (issue_id) REFERENCES daily_issues(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS biz_issues (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  issue_date DATE NOT NULL,
  title VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS biz_items (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  issue_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary TEXT NOT NULL,
  score INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (issue_id) REFERENCES biz_issues(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS biz_tags (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  biz_item_id BIGINT NOT NULL,
  tag VARCHAR(64) NOT NULL,
  FOREIGN KEY (biz_item_id) REFERENCES biz_items(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS profiles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  display_name VARCHAR(128) NOT NULL,
  bio TEXT NOT NULL,
  avatar VARCHAR(500) NOT NULL,
  location VARCHAR(64) NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS profile_links (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  profile_id BIGINT NOT NULL,
  title VARCHAR(128) NOT NULL,
  url VARCHAR(500) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS site_settings (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  profile_id BIGINT NOT NULL,
  theme VARCHAR(32) NOT NULL DEFAULT 'system',
  lang VARCHAR(16) NOT NULL DEFAULT 'zh-CN',
  show_biz_entry TINYINT(1) NOT NULL DEFAULT 1,
  FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS robot_configs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  schedule_cron VARCHAR(64) NOT NULL,
  source_urls JSON NOT NULL,
  ai_model VARCHAR(128) NOT NULL,
  prompt_template TEXT NOT NULL,
  max_items INT NOT NULL DEFAULT 30,
  auto_publish TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS crawl_jobs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  robot_id BIGINT NOT NULL,
  status VARCHAR(32) NOT NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at DATETIME NULL,
  message TEXT NULL,
  FOREIGN KEY (robot_id) REFERENCES robot_configs(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS crawl_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  crawl_job_id BIGINT NOT NULL,
  source_url VARCHAR(500) NOT NULL,
  raw_title VARCHAR(255) NOT NULL,
  raw_content LONGTEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (crawl_job_id) REFERENCES crawl_jobs(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ai_generation_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  crawl_job_id BIGINT NOT NULL,
  model_name VARCHAR(128) NOT NULL,
  prompt_text LONGTEXT NOT NULL,
  output_json LONGTEXT NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (crawl_job_id) REFERENCES crawl_jobs(id) ON DELETE CASCADE
);
